const path = require('path');

const APPS_ROOT = process.env.DARK_AVIAN_APPS_ROOT || '/var/www/development';

module.exports = {
  apps: [
    {
      name: '[DEV] Auth',
      namespace: 'dark-avian-labs-dev',
      script: './dist/server/index.js',
      cwd: path.join(APPS_ROOT, 'auth'),
      interpreter: 'node',
      node_args: '--env-file=.env',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 3,
      min_uptime: '10s',
      listen_timeout: 10000,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'development',
        PORT: '4000',
      },
    },
    {
      name: '[DEV] Codex',
      namespace: 'dark-avian-labs-dev',
      script: './dist/server/index.js',
      cwd: path.join(APPS_ROOT, 'codex'),
      interpreter: 'node',
      node_args: '--env-file=.env',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 3,
      min_uptime: '10s',
      listen_timeout: 10000,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'development',
        PORT: '4001',
      },
    },
    {
      name: '[DEV] Armory',
      namespace: 'dark-avian-labs-dev',
      script: './dist/server/index.js',
      cwd: path.join(APPS_ROOT, 'armory'),
      interpreter: 'node',
      node_args: '--env-file=.env',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 3,
      min_uptime: '10s',
      listen_timeout: 10000,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'development',
        PORT: '4002',
      },
    },
  ],
};
